name: Frontend Tests

on: [pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies (frontend)
              run: npm install
              working-directory: frontend
            - name: Install dependencies (backend)
              run: npm install
              working-directory: backend
            - name: Run backend
              run: npm start
              working-directory: backend
            - name: Run tests
              run: npm test
              working-directory: frontend